Repository Paulmski/Discord-Bot, pull requests merged in 2022-01, with the labels that each got.

#52 Bug Fixes #49 and #50: Announcement Embed and Study Group Logic
  src/__main__.py
  src/classes/Course.py
  src/classes/DBManager.py
  src/classes/User.py
  src/events.py
  src/sheets_parser.py
Labels: bug

#59 Develop
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  src/__main__.py
  src/classes/Course.py
  src/classes/DBManager.py
  src/classes/Group.py
  src/classes/User.py
  src/events.py
  src/gsapi_builder.py
  src/sheets_parser.py
Labels: enhancement

#63 Bug #62: Repeating headers for !list
  src/__main__.py
  src/events.py
Labels: bug

#75 Refactoring, improve `!list`, and announcement
  .github/workflows/codeql-analysis.yml
  src/__main__.py
  src/classes/Assignment.py
  src/classes/Course.py
  src/events.py
Labels: bug, enhancement
